PORTNAME=	iavf
PORTVERSION=	3.1.2
PORTEPOCH=	0
MASTER_SITES?=	https://downloadmirror.intel.com/843931/

MAINTAINER=	freebsd@intel.com
COMMENT=	40G and 100G FreeBSD Driver for Virtual Function for Intel NIC

MASTERDIR=	${.CURDIR}/../intel-ixl-kmod
PATCHDIR=	${.CURDIR}/files
PKGDIR=		${.CURDIR}
DISTINFO_FILE=	${.CURDIR}/distinfo
WRKSRC_SUBDIR=
MANPAGENAME=	iavf
MANPAGELINKS=	if_iavf

.include "${MASTERDIR}/Makefile"
